<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AttestatiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Assegna tutti gli attestati all'utente principale (ID = 1)
        DB::table('attestati')->insert([
            [
                'user_id'       => 1,
                'title'         => 'Data Week',
                'description'   => 'Conoscenza di Python e Tableau',
                'poster'        => 'attestati/1 - Boolean/poster.webp',
                'poster_alt'    => 'Certificazione di Boolean',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Boolean',
                'issued_at'     => '2023-11-24',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Python',
                'description'   => 'Conoscenza di Python base',
                'poster'        => 'attestati/2 - ProfessionAI/poster.webp',
                'poster_alt'    => 'Certificazione di Profession AI',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Profession AI',
                'issued_at'     => '2023-11-24',
                'expires_at'    => null,
                'credential_id' => '66db79ef3e63de5973000047',
                'credential_url'=> 'https://mycourse.app/w1koBRbGnJNfLV3u6',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Progettazione BIM',
                'description'   => 'Conoscenza di BIM - fatturazione Elettronica',
                'poster'        => 'attestati/3 - Acca/poster.webp',
                'poster_alt'    => 'Certificazione di Acca',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Acca',
                'issued_at'     => '2018-12-18',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Node.js',
                'description'   => '"All you need is Node.js" Attendee',
                'poster'        => 'attestati/4 - weBeetle/poster.webp',
                'poster_alt'    => 'Certificazione di Node.js',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'weBeetle',
                'issued_at'     => '2025/10/22',
                'expires_at'    => null,
                'credential_id' => 'AdEMa-ETQmayfrkwlP1PLA',
                'credential_url'=> 'https://api.eu.badgr.io/public/assertions/AdEMa-ETQmayfrkwlP1PLA',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Chatbot con GPT-4',
                'description'   => 'Creazione di un chatbot con GPT4 iniziando da javascript e API di Openai',
                'poster'        => 'attestati/5 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinad di Chatbot con GPT-4 iniziando da javascript e API di Openai',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/09/19',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01j856tpm6taepdf71xsfhybyb',
                'credential_url'=> 'https://mycertcloud.com/check/01j856tpm6taepdf71xsfhybyb',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Python',
                'description'   => 'Conoscenza di Python base',
                'poster'        => 'attestati/6 - hackerrank/poster.webp',
                'poster_alt'    => 'Certificazione di hackerrank',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'hackerrank',
                'issued_at'     => '2024/09/15',
                'expires_at'    => null,
                'credential_id' => 'BFFE3E583BFC',
                'credential_url'=> 'https://www.hackerrank.com/certificates/bffe3e583bfc',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Full Stack Web Developer',
                'description'   => 'Corso Hackademy HTML,CSS, Javascript, PHP, Framework laravel e Metodologie Agili',
                'poster'        => 'attestati/7 - Aulab/poster.webp',
                'poster_alt'    => 'Certificazione di Web Developer di Aulab',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Accredible',
                'issued_at'     => '2024/07/12',
                'expires_at'    => null,
                'credential_id' => '0x5bc14254968b01072772062dc940a556a2f724e795592d8272d9c188f0e2099f',
                'credential_url'=> 'https://www.credential.net/4231ae3b-e3af-46f0-9cee-78bfa5f00b80#gs.er8z0p',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Corso di TypeScript',
                'description'   => 'Corso completo di TypeScript, partendo dalle basi fino agli aspetti avanzati del linguaggio',
                'poster'        => 'attestati/8 - FabioBiondi/poster.webp',
                'poster_alt'    => 'Corso di Typescript di Fabio Biondi',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => null,
                'issued_at'     => '2025/05/30',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Coding + AI',
                'description'   => 'Confronto tra Web Developer e Vibe Developer',
                'poster'        => 'attestati/9 - Aulab/poster.webp',
                'poster_alt'    => 'Seminario di confronto tra Web Developer e Vibe Developer',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Aulab',
                'issued_at'     => '2025/10/21',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'BIM e NTC 2018',
                'description'   => 'Piattaforme collaborative per la direzione Lavori',
                'poster'        => 'attestati/10 - Acca/poster.webp',
                'poster_alt'    => 'Seminario di Acca per BIM e NTC 2018',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Acca',
                'issued_at'     => '2018/12/18',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Angular Evolution',
                'description'   => 'Corso di Angular dalle basi ad esperto',
                'poster'        => 'attestati/11 - FabioBiondi/poster.webp',
                'poster_alt'    => 'Corso Angular Evolution di Fabio Biondi',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'Fabio Biondi',
                'issued_at'     => '2025/07/26',
                'expires_at'    => null,
                'credential_id' => null,
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Symfony php',
                'description'   => 'Symfony per la pianificazione di task ricorrenti',
                'poster'        => 'attestati/12 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinar di Symfony per la pianificazione di task ricorrenti',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/09/24',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01j8m9dtvwse6ys865gd8tcd82',
                'credential_url'=> 'https://mycertcloud.com/check/01j8m9dtvwse6ys865gd8tcd82',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Chatbot con GPT-4',
                'description'   => 'Creazione di un chatbot con GPT4 - integrando un database vettoriale',
                'poster'        => 'attestati/13 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinar di Chatbot con GPT-4 integrando un database vettoriale',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/09/25',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01j8psbhkn03g6pvzhhtpc7g93',
                'credential_url'=> 'https://mycertcloud.com/check/01j8psbhkn03g6pvzhhtpc7g93',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Chatbot con GPT-4',
                'description'   => 'Creazione di un chatbot con GPT4 - AI agent con langchain',
                'poster'        => 'attestati/14 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinar di Chatbot con GPT-4 AI agent con langchain',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/10/09',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01j9xk0gnzp2sxnwhfc0djnmme',
                'credential_url'=> 'https://mycertcloud.com/check/01j9xk0gnzp2sxnwhfc0djnmme',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Javascript Map e Set',
                'description'   => 'Coding in  live con Javascript Map e Set',
                'poster'        => 'attestati/15 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinar di Chatbot con GPT-4 AI agent con langchain',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/10/23',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01jaz8dvw9sqphdt03xw81pff7',
                'credential_url'=> 'https://mycertcloud.com/check/01jaz8dvw9sqphdt03xw81pff7',
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'user_id'       => 1,
                'title'         => 'Symfony protezione dei dati',
                'description'   => 'Conoscenza specifica per la protezione dei dati con Symfony',
                'poster'        => 'attestati/16 - TheCommunitiesBay/poster.webp',
                'poster_alt'    => 'Webinar di Symfony per la protezione dei dati',
                'poster_w'      => 1200,
                'poster_h'      => 1600,
                'poster_lqip'   => null,
                'issuer'        => 'The Communities Bay',
                'issued_at'     => '2024/11/19',
                'expires_at'    => null,
                'credential_id' => 'MYCERTCLOUD-01jd4phr4nkpz6e72xhhpg6emm',
                'credential_url'=> null,
                'status'        => 'published',
                'is_featured'   => true,
                'sort_order'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ]
        ]);
    }
}
